export { default as AuthorizationPage } from './authorization/AuthorizationPage'
export { default as HistoryPage } from './history/HistoryPage'
export { default as HomePage } from './home/HomePage'
export { default as ProfilePage } from './profile/ProfilePage'
export { default as RegisterPage } from './register/RegisterPage'
